name: Quick Build

on:
  push:
  pull_request:

jobs:
  quick-build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
    
    - name: Build
      run: |
        mkdir build && cd build
        cmake ..
        make -j$(nproc)
    
    - name: Test
      run: |
        cd build
        ./nightforge --help
        timeout 2s ./nightforge --min-width 10 --min-height 5 || echo "Engine test completed"

  quick-build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up MSYS2 (MINGW64)
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64

    - name: Install dependencies
      shell: bash
      run: |
        pacman --noconfirm -Syuu
        pacman --noconfirm -S --needed mingw-w64-x86_64-toolchain mingw-w64-x86_64-cmake mingw-w64-x86_64-make
        echo "export PATH=/mingw64/bin:$PATH" >> $GITHUB_ENV

    - name: Configure & Build
      shell: bash
      run: |
        mkdir build && cd build
        cmake ..
        make -j$(nproc)

    - name: Test
      shell: bash
      run: |
        cd build
        ./nightforge --help || true
        timeout 2s ./nightforge --min-width 10 --min-height 5 || echo "Engine test completed"