name: Test ASCII Converter

on:
  push:
    paths:
      - 'tools/**'
      - 'src/rendering/**'
  pull_request:
    paths:
      - 'tools/**'
      - 'src/rendering/**'

jobs:
  test-converter:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential imagemagick
    
    - name: Create test image
      run: |
        # Create a simple test image using ImageMagick
        convert -size 64x32 xc:white -fill black -gravity center -pointsize 20 -annotate +0+0 "TEST" test.png
    
    - name: Build converter
      run: |
        mkdir build && cd build
        cmake ..
        make webp_to_ascii -j$(nproc)
    
    - name: Test ASCII conversion
      run: |
        cd build
        ./webp_to_ascii ../test.png clean no 40
        echo "✓ ASCII conversion successful"
    
    - name: Test different styles
      run: |
        cd build
        echo "Testing clean style:"
        ./webp_to_ascii ../test.png clean no 30
        echo -e "\nTesting high_fidelity style:"
        ./webp_to_ascii ../test.png high_fidelity no 30
        echo -e "\nTesting block style:"
        ./webp_to_ascii ../test.png block no 30
        echo "✓ All styles work"

  test-converter-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Attempt to install ImageMagick
      shell: pwsh
      run: |
        try {
          choco install imagemagick -y
        } catch {
          Write-Warning "choco or ImageMagick not available in runner, some tests may be skipped"
        }

    - name: Build converter
      shell: bash
      run: |
        mkdir build && cd build
        cmake ..
        cmake --build . --config Release --target webp_to_ascii -- /m

    - name: Test ASCII conversion
      shell: pwsh
      run: |
        Set-Location build\Release
        $exe = Join-Path (Get-Location) "webp_to_ascii.exe"
        if (-not (Test-Path $exe)) { Write-Warning "webp_to_ascii.exe not found; skipping test"; exit 0 }
        # Create a small PNG using PowerShell's built-in methods if ImageMagick not available
        $testPng = "$(Get-Location)\..\test.png"
        if (-not (Test-Path $testPng)) {
          try {
            Add-Type -AssemblyName System.Drawing
            $bmp = New-Object System.Drawing.Bitmap 64,32
            $g = [System.Drawing.Graphics]::FromImage($bmp)
            $g.Clear([System.Drawing.Color]::White)
            $font = New-Object System.Drawing.Font 'Arial', 20
            $brush = [System.Drawing.Brushes]::Black
            $g.DrawString('TEST', $font, $brush, 5,5)
            $bmp.Save($testPng, [System.Drawing.Imaging.ImageFormat]::Png)
            $g.Dispose(); $bmp.Dispose()
          } catch {
            Write-Warning "Could not create test PNG; skipping converter test"
            exit 0
          }
        }

        & .\webp_to_ascii.exe ..\test.png clean no 40
        Write-Output "✓ ASCII conversion successful on Windows"